repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  # - id: check-added-large-files
  - id: check-ast
  - id: detect-private-key
  - id: double-quote-string-fixer
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: 'v0.31.0'
  hooks:
  - id: yapf
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: 'v0.991'
#   hooks:
#   - id: mypy
#     args: [--no-strict-optional]
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.0
