---
xgb_params:
  tree_method: gpu_hist
  gpu_id: 0
  nthread: 50
  learning_rate: 0.22502761577232197
  max_depth: 8
  objective: reg:squarederror
  min_child_weight: 2.8420515790248526
  subsample: 0.975
  colsample_bytree: 0.75
  colsample_bylevel: 0.925
  gamma: 0.001531824642793309
  reg_lambda: 0.010527402680638263
  reg_alpha: 1.2647545029756599e-08
lgb_params:
  boosting_type: gbdt
  lambda_l1: 3.035082410337794e-05
  lambda_l2: 2.7222837773047282e-08
  num_leaves: 256
  feature_fraction: 0.7532144343509061
  bagging_fraction: 0.9735502443957263
  bagging_freq: 3
  min_child_samples: 25
  verbose: 0
  learning_rate: 0.1
  objective: regression
  metric: rmse
  num_threads: 50
  force_col_wise: true
cat_params:
  learning_rate: 0.17447854966066342
  objective: RMSE
  colsample_bylevel:
  depth: 12
  boosting_type: Plain
  bootstrap_type: Bernoulli
  subsample: 0.9709524520446949
  use_best_model: true
  eval_metric: RMSE
  thread_count: 50
  task_type: GPU
  devices: '0:1:2'
